services:
  gddemotokens:
    runtime: nvidia
    command: /usr/sbin/sshd -D
    image: gddemotokens
    shm_size: 8gb
    environment:
    - HOME=/root
    - USER=$USER
    volumes:
    - /home/yzahran/GroundingDinoTrainEmbeddings:/GroundingDinoTrainEmbeddings
    - $HOME:/root
    - $PWD:/home/yzahran/GroundingDinoTrainEmbeddings
    - /usr/local/certificates:/certificates
    - $HOME/.ssh/authorized_keys:/root/.ssh/authorized_keys


    ports:
    - "11512"
version: '2.3'
